services:
  api-new:
    amazeeio:
      type: custom
      template: services/api/.amazeeio.app.yml
    build:
      dockerfile: services/api/Dockerfile
  api:
    amazeeio:
      type: custom
      template: services/api-legacy/.amazeeio.app.yml
    build:
      dockerfile: services/api-legacy/Dockerfile
  elasticsearch:
    amazeeio:
      type: custom
      template: services/elasticsearch/.amazeeio.app.yml
    build:
      dockerfile: services/elasticsearch/Dockerfile
  kibana:
    amazeeio:
      type: custom
      template: services/kibana/.amazeeio.app.yml
    build:
      dockerfile: services/kibana/Dockerfile
  logs2slack:
    amazeeio:
      type: custom
      template: services/logs2slack/.amazeeio.app.yml
    build:
      dockerfile: services/logs2slack/Dockerfile
  logstash:
    amazeeio:
      type: custom
      template: services/logstash/.amazeeio.app.yml
    build:
      dockerfile: services/logstash/Dockerfile
  openshiftdeploy:
    amazeeio:
      type: custom
      template: services/openshiftdeploy/.amazeeio.app.yml
    build:
      dockerfile: services/openshiftdeploy/Dockerfile
  openshiftdeploy-legacy:
    amazeeio:
      type: custom
      template: services/openshiftdeploy-legacy/.amazeeio.app.yml
    build:
      dockerfile: services/openshiftdeploy-legacy/Dockerfile
  openshiftremove:
    amazeeio:
      type: custom
      template: services/openshiftremove/.amazeeio.app.yml
    build:
      dockerfile: services/openshiftremove/Dockerfile
  openshiftremove-legacy:
    amazeeio:
      type: custom
      template: services/openshiftremove-legacy/.amazeeio.app.yml
    build:
      dockerfile: services/openshiftremove-legacy/Dockerfile
  rabbitmq:
    amazeeio:
      type: custom
      template: services/rabbitmq/.amazeeio.app.yml
    build:
      dockerfile: services/rabbitmq/Dockerfile
  rest2tasks:
    amazeeio:
      type: custom
      template: services/rest2tasks/.amazeeio.app.yml
    build:
      dockerfile: services/rest2tasks/Dockerfile
  webhook-handler:
    amazeeio:
      type: custom
      template: services/webhook-handler/.amazeeio.app.yml
    build:
      dockerfile: services/webhook-handler/Dockerfile
  webhooks2tasks:
    amazeeio:
      type: custom
      template: services/webhooks2tasks/.amazeeio.app.yml
    build:
      dockerfile: services/webhooks2tasks/Dockerfile
