docker-compose-yaml: docker-compose.yaml

additional-yaml:
  secrets:
    path: .lagoon.secrets.yaml
    command: create
    ignore_error: true
tasks:
  post-rollout:
    - run:
        name: 'check\set kibana index patterns'
        command: cd /lagoon/kibana-init/; index-patterns.sh
        service: logs-db-ui
    - run:
        name: 'check\set elasticsearch watchers'
        command: cd /lagoon/kibana-init/; watchers.sh
        service: logs-db-ui
