docker-compose-yaml: docker-compose.yaml

additional-yaml:
  secrets:
    path: .lagoon.secrets.yaml
    command: create
    ignore_error: true

  logs-db-secrets:
    path: .lagoon.logs-db-secrets.yaml
    command: create
    ignore_error: true

  keycloak-secrets:
    path: .lagoon.keycloak-secrets.yaml
    command: create
    ignore_error: true

tasks:
  post-rollout:
    - run:
        name: update database schema
        command: /rerun_initdb.sh
        service: api-db
    - run:
        name: 'check\set kibana index patterns'
        command: cd /lagoon/kibana-init/; sh index-patterns.sh
        service: logs-db-ui
    - run:
        name: 'check\set elasticsearch watchers'
        command: cd /lagoon/kibana-init/; sh watchers.sh
        service: logs-db-ui

environments:
  master:
    types:
      logs-db: elasticsearch-cluster
    templates:
      logs-db: services/logs-db/.lagoon.cluster.yml
      logs-forwarder: services/logs-forwarder/.lagoon.multi.yml
    rollouts:
      logs-db: statefulset
      logs-forwarder: statefulset
    cronjobs:
      - name: idle-clis
        schedule: '*/15 * * * *'
        command: /idle-clis.sh
        service: auto-idler
      - name: idle-services
        schedule: '*/30 * * * *'
        command: /idle-services.sh
        service: auto-idler
      - name: curator
        schedule: '01 0 * * * '
        command: /usr/bin/curator --config curator.yml actions.yml
        service: logs-db-curator
