sudo: required
services:
- docker
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- sudo sh -c "echo \"DOCKER_OPTS='--insecure-registry 172.30.0.0/16'\" >> /etc/default/docker" && sudo service docker restart && sudo mount --make-rshared /
- docker info
- docker version
- docker login -u amazeeiojenkins -p $DOCKERHUB_PASSWORD
install:
- make pull -j6 TAG=$TRAVIS_BRANCH
- docker image ls -a --digests
before_script:
- make openshift
script:
- docker logs -f origin &> .openshift-logs &
- make build TAG=$TRAVIS_BRANCH
- make tag-push TAG=$TRAVIS_BRANCH &> .push-logs &
- make up
- docker-compose -p lagoon logs -f &> .service-logs &
- sleep 60
- make tests
after_script:
- cat .build-logs
- cat .openshift-logs
- cat .push-logs
- cat .service-logs
notifications:
  slack:
    secure: XavhNWfkLB2MfuEg6UrIZ6jz3NNRr9drcyOWlI75wB2iPuP7C/rGrZ1NZJNjGvykM7JvZqcfD+tyzolP+MgzIthJF51mooC8QyfZc1BoiS2uhg+hD/g3COB+XbRnHv76Q4I42KRP/vHM2quNaW79VWovyCoTcWzJqVpKnLvs26asl38+5Z0oYGXTROC6c5rfow8aAsix1ZatCwugOQmVmepsKpLjNpiSv1OyWeIqURkqTxO2Q/Pw6Kow6O0DZZZW75swDNbNeC4OK4mZiGj5yPFRpiVqz1DHIWYAvCzkMVqgxubn5Ob/cDlkY306XGauetOlfx2SgL1FN4sbVFnu9t2JZJXj+Zzg7ccoGtN3rlfIpoUGb4U6hIQFmLky8XnZYnEF1D+n9ld3/y5WV7qOeVYTZsf5nEopD1Kq/8Zc+Hi6VJZ1nZEaovlLL2USnWfo4E/PlO3hSTF/9FEPy2JyWuExdcBxxTBWwgNwihBvpEyFG+YeryNR2kAlax8cRi8inhHLIBg+PhSDFB5r/kMjwDYqWQ/uTIFxLbZa+s1TEhNspPaeyDJkj8wYnlrlWuAC9fDppFFM8BbZrK1Lc6nIY0VMFVZOyKug6TW3/Jy2iKY1D0+EoCg78qHWn9xnXWfMugQKKLz+/p+WocC9HTiijYbqWtuUPBupF5SQpCQhw+0=