version: '2'
services:
  webhook-handler:
    build: services/webhook-handler
    command: bash -c "yarn run link-node-packages && yarn run dev"
    ports:
      - "7777:3000"
    links:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./services/webhook-handler/src:/app/services/webhook-handler/src
      - ./node-packages:/app/node-packages
  rabbitmq:
    build: services/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - HOSTNAME=rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
#  gitpush2ansibledeploy:
#    build: services/gitpush2ansibledeploy
#    command: yarn run dev
#    links:
#      - rabbitmq
#      - api
#      - jenkins
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#      - AMAZEEIO_API_HOST=http://api:8080
#      - JENKINS_URL=http://admin:admin@jenkins:8080
#      - DOCKER_RUN_PARAM=--add-host deploytest1.compact.amazee.io:172.28.128.99
#      - ANSIBLE_IMAGE_LOCATION=absolute
#    volumes:
#      - ./services/gitpush2ansibledeploy/src:/app/src
  openshiftremove:
    build: services/openshiftremove
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
      - api
      - jenkins
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
      - JENKINS_URL=http://admin:admin@jenkins:8080
    volumes:
      - ./services/openshiftremove/src:/app/services/openshiftremove/src
      - ./node-packages:/app/node-packages
  openshiftremove-legacy:
    build: services/openshiftremove-legacy
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
      - api
      - jenkins
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
      - JENKINS_URL=http://admin:admin@jenkins:8080
    volumes:
      - ./services/openshiftremove-legacy/src:/app/services/openshiftremove/src
      - ./node-packages:/app/node-packages
  openshiftdeploy:
    build: services/openshiftdeploy
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
      - api
      - jenkins
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
      - JENKINS_URL=http://admin:admin@jenkins:8080
      - OC_BUILD_DEPLOY_IMAGE_LOCATION=absolute
      - DOCKER_RUN_PARARM=--network=lagoon_default
    volumes:
      - ./services/openshiftdeploy/src:/app/services/openshiftdeploy/src
      - ./node-packages:/app/node-packages
  openshiftdeploy-legacy:
    build: services/openshiftdeploy-legacy
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
      - api
      - jenkins
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
      - JENKINS_URL=http://admin:admin@jenkins:8080
      - OC_BUILD_DEPLOY_IMAGE_LOCATION=absolute
      - DOCKER_RUN_PARARM=--network=lagoon_default
    volumes:
      - ./services/openshiftdeploy-legacy/src:/app/services/openshiftdeploy/src
      - ./node-packages:/app/node-packages
  logs2slack:
    build: services/logs2slack
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
      - api
      - jenkins
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
    volumes:
      - ./services/logs2slack/src:/app/services/logs2slack/src
      - ./node-packages:/app/node-packages
  webhooks2tasks:
    build: services/webhooks2tasks
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
      - api
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
    volumes:
      - ./services/webhooks2tasks/src:/app/services/webhooks2tasks/src
      - ./node-packages:/app/node-packages
  rest2tasks:
    build: services/rest2tasks
    command: bash -c "yarn run link-node-packages && yarn run dev"
    links:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
    volumes:
      - ./services/rest2tasks/src:/app/services/rest2tasks/src
      - ./node-packages:/app/node-packages
    ports:
      - "5555:3000"
  api:
    build: services/api
    command: yarn run dev
    environment:
      - GIT_REPOSITORY=file:///lagoon/hiera
      - GIT_BRANCH_PULL=ci-local
    volumes:
      - ./services/api/src:/app/src
      - .:/lagoon
    ports:
      - "8080:3000"
  jenkins:
    build: services/jenkins
    environment:
      - JENKINS_ADMIN_PASSWORD=admin
    ports:
      - "8888:8080"
  jenkins-slave:
    build: services/jenkins-slave
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-executors/ansible-drupal-deploy:/ansible-drupal-deploy
      - ./docker-executors/docker-oc-build-deploy:/docker-oc-build-deploy
    links:
      - jenkins
    environment:
      - JENKINS_MASTER_CREDENTIALS=admin:admin
      - JENKINS_MASTER_URL=http://jenkins:8080
      - JENKINS_SLAVE_NAME=alpha
  tests:
    build: tests
    links:
      - webhook-handler
      - git
    environment:
      - WEBHOOK_HOST=webhook-handler
      - WEBHOOK_PORT=3000
      - WEBHOOK_PROTOCOL=http
      - REST2TASKS_HOST=rest2tasks
      - REST2TASKS_PORT=3000
      - REST2TASKS_PROTOCOL=http
      - OPENSHIFT_ROUTE_SUFFIX=192.168.77.100.nip.io
      - GIT_REPO_PREFIX=git@git:/git/
      - SSH_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEAuW/QMG+osFkc9c/kA8C5Ur7acYP+6Ue0X/pCU95IUBoi7l+E\nJNmgwq7dXyp3Y8lLo+eaHEXPDpRMawPBT32W6Z32jV31YfU5cm4YyFlB7S23PYIg\nqA7oldkxG+mVv3rCpVbVqJs32P548DwLlxFNot4+WMVULmdMvgDeMnGuFdcu8tgZ\nVDr6eakr8//D3ASXoGqHrEkrhaUFgke/PP4tLFESYmhuvrWTfmxlUpyYLW10Cb3N\nK+OWrtzy+Y8jHAKWxzgg0FCIlsguoqVthCGE1AVTvNEFRI8ppgWaWREJf9A0DxMw\nXagouF+MJsIaGp+4UCUO3TXapkS/luC++cjzcp4DYCVTU5SFzh13r6TbJB//x1Jc\nBKeFjx7k++gWU93KtUQmrZ+ojLBYsKREpPccg2xFT38SgK++3EaRSB7iXe2pg405\nO/yj9D05YjtlYgsow7nYmo8DYe15mNGamK4RyNenm00hEg7JYdGtCZWb1pWGuMQw\nSrSsHyDUa3K2JrmFM0he8J+xdaOOXB2dpLn7YqDkISzYMdC6s7UTJ90QaHht0B28\nZr/Vnzv9IR2uBXZECxKxHcxDPSUeFnsEZ4dOHXI3o19XWlim6Nl/J3WgnNAb3TQy\n/x6UoKnwpydjZauKTOj6JpL3aecE1qWcAow5dPFILbQBa0MI2KAcvVKVJg0CAwEA\nAQKCAgEAnoFv8GcRRyP0+DyqR3buMkeHCy7rrtWm3b9aALxpDWc54o3ss17+5kp4\nWQdApCAFMuYeOfqF4Y1rwLGmBF9ypuBqRi5BOGlXoHNxZZe+HZFNJxta9KxBrQzI\nyHYilVjGlnOiEAwVcbsa/yYkNg4JUaUsn86UhVGxLFwrkezQBEU6EUQcan47adDs\nDBXcge2++dT1gZPNyt/i1JilY+pUDKSD1XA08XjdyVu4RCQsg/AiFs2RWemg/HlK\ni30JYsDnxwQ4MDgWeORF0Ksc8KuCEYU4LZZxLUg+LnZtl6JTf1gll5ksZ3H81JR/\nhQW3MHjEIGV8ziNhcWwkZEBZncNiK2tNYuY6LiLJuGWLNZm+iySW6FnO8UE1wOg4\nt9n+D37A7dAbm39c92oej2uOWilbXjhuHJUFUPtgMDZJAvLxMtPliF9dFG5l8Kly\nuvYaTg1L5DuekOP8HjNuWwV3Wb21jeW0A/RUf7h/VKq/q/F3BbQE6wyxDUVofsMF\n9fwYqrrOMKIXPsnhk46i43TW2r3ygaYv2q56B2uM0mhfeHbrHjqnUwUS/l9cp8YC\ncsOsTn8AYCHe5fo1zv7Xto/C83wV6qQLwqOpWVkvaVYoGwhBFeTYHpV1/ata4UKA\nOtO6cAC/M9DrnWHKjhdmEshqni/G2niab8OkZkMZvRuBtD5r9bUCggEBAN5QRWnk\nBG8SRcPq87eul1pTSwoIDj1ya3CPxdI7YFCiwblYbg7dfsuEK+iSVRQCl4vGs1gR\nVLwyVNBYvl9AInKvH1zeBVXLKOwafz/ddPElbMkhjsKIc7ipvQ5HIY4rPaJCklol\nuhDD0315rmd62fh3B1fSZaJ8ARwRraavmpaMsZvaDLIeA7iiG7mm+YYsjI6G2HW3\nHR7V7sTBq/yIY5YJUtBjZRxi5E0hkRmX3xmy/rEaBsyFhTBBqrHzlfun1dr1nJbh\naTocMdvPb1uByy+PQ/u6V1k3asEAUDEBSDAQWGylivINObXJ7SRQD9UibsqA6J9j\nwrXLkkTINSP6JJsCggEBANWJD4T60kGZC8A5Fhz7wgBh/NNKxIY4eYkQCWSud0iW\ncZ7TChIcBj5V/WQiVt8IGc4c7cPkvhHu66ZPBChUNj0BG5xNzBkpILi3zn3x5qRB\ntiISFI6DOoHNfma05Ok9KJI2v4vS6e1BLIF34Npi0KoxOfycJVb3N4jQLBc5eZSr\nbvyD74/3BByWFNvr4sE1PpTo6Hs5WOzTXzi0qinhOPDc4TwCbr4ggiKzsQAzqU4z\nEXY37pUeH7CTHSBidCaW47m428T5VJSL3TFKwYcuE7ZkprjQT0FiLgea4/+KQ0US\nMFUM6OO/4qtKcuocDGe+Mrut3T0kCmnSosIxx3g/hncCggEAYB/TM6r8483Bzqmb\ngdOC6/JR4t+C0LzVidEQlwtHZPZKz0pWJCVPes4GckQ7dzB7uFtNFoo/2jPlCkUk\n42iGvJHN/MifA+6ZHiWC2el2dAJbnEffQ2vepXz3GuJUtvUpbCxevY3Mew1BN+LS\nLzomX1GQIj/95Bi8Hhfivsz1CZ2B+kJ49NcXgtDNLiPthj9i8wmJNLTdaYTU/cxE\nAigy7x/O5/3iLTjxQAyAgdFyDNmhWJBJWkttQGVUWidZtXtnc4p5j5+dcRvZzxJN\nMwLXCRRoL8Ltm8zjYtow0k+cl/OpWCjoACsJxfmuiOH5Ro3h27uLWce33AVOlGEA\n4TJ6ewKCAQAScrryhDDyFeTcAJKWgnGqUszi/EyqQ+rMGqSVHDWWAdljHVx7YAxy\nCj/QDN9weWSxV/J6wCJjrj6RqbX0PgJJlvTpthbx/YmkK80dOG7ytfKkUuePwGqn\nmDdZbDtyoyQELdKyo9At/Tl5HgBBHdRlP8eAuYTIVKdpnIKSpxaH75+xFTz3NSIX\nzieTMHfwtUbo2o5rRvMV0tUhMwqYf6rJtGuJIbSrnGdh1CBwogX4iZTyn7ZvD6Ex\nQiR8DcV3KAYYn43tIJVcGBFOFuVNZn+xfFSjFuwh+/d6FLmp9CoHp6ChWHIuav+M\nSOxQqYew1s/PQyAgDiMQLXB+UoqnKuXVAoIBAQCBRcSjXWseY+/Uvqj+41kKcEFL\nT7AuJcrb9fpN0EYbrTlaU1yVDfYxnRn4Pw2de1XE/S2dngvriraFHrY/fnyRqM5C\ns/1QnzAjb+y/Vvvt/RaDYXwpm8KpSrd3vqwj7TsoYgWiSvmbjYOg6Gt8QJZNmfhS\nYexGNfR/Zr8jdK9ZC6Tqwt2yUuBtVS3wWmX7Dqz3/kAfJ+tNp7CQNGw7TOMXH071\nfU/ZNna8w+9G3mxSRWM+wxIg7pPZ4floXVJGTcYl6+pG8a1saUNRwx72+pt3XUMD\nXYS+IJhFCIXCuehmfDIp7Fe8Ed2s1QDbF/vdc+icTah12SF/XhZ+6clY8j2Y\n-----END RSA PRIVATE KEY-----
    volumes:
      - ./tests:/ansible
  git:
    build: local-git-server
    environment:
      - GIT_AUTHORIZED_KEYS=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5b9Awb6iwWRz1z+QDwLlSvtpxg/7pR7Rf+kJT3khQGiLuX4Qk2aDCrt1fKndjyUuj55ocRc8OlExrA8FPfZbpnfaNXfVh9TlybhjIWUHtLbc9giCoDuiV2TEb6ZW/esKlVtWomzfY/njwPAuXEU2i3j5YxVQuZ0y+AN4yca4V1y7y2BlUOvp5qSvz/8PcBJegaoesSSuFpQWCR788/i0sURJiaG6+tZN+bGVSnJgtbXQJvc0r45au3PL5jyMcApbHOCDQUIiWyC6ipW2EIYTUBVO80QVEjymmBZpZEQl/0DQPEzBdqCi4X4wmwhoan7hQJQ7dNdqmRL+W4L75yPNyngNgJVNTlIXOHXevpNskH//HUlwEp4WPHuT76BZT3cq1RCatn6iMsFiwpESk9xyDbEVPfxKAr77cRpFIHuJd7amDjTk7/KP0PTliO2ViCyjDudiajwNh7XmY0ZqYrhHI16ebTSESDslh0a0JlZvWlYa4xDBKtKwfINRrcrYmuYUzSF7wn7F1o45cHZ2kuftioOQhLNgx0LqztRMn3RBoeG3QHbxmv9WfO/0hHa4FdkQLErEdzEM9JR4WewRnh04dcjejX1daWKbo2X8ndaCc0BvdNDL/HpSgqfCnJ2Nlq4pM6Pomkvdp5wTWpZwCjDl08UgttAFrQwjYoBy9UpUmDQ== ansible-testing
    expose:
      - "22"
  elasticsearch:
    build: services/elasticsearch
    user: '1000'
    environment:
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"
  kibana:
    build: services/kibana
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
  logstash:
    build: services/logstash
    user: '1111722'
    links:
      - elasticsearch
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
  hacky-rest2tasks-ui:
    build: services/hacky-rest2tasks-ui
    command: yarn run dev
    environment:
      - API=http://api:3000
      - REST2TASKS_URL=http://rest2tasks:3000
    volumes:
      - ./services/hacky-rest2tasks-ui/app:/app/app
    links:
      - rest2tasks
    ports:
      - "8090:3000"
  jobwatch:
    build: services/jobwatch
    command: yarn run dev
    ports:
      - "8300:3000"
    links:
      - rabbitmq
      - api
    environment:
      - RABBITMQ_HOST=rabbitmq
      - AMAZEEIO_API_HOST=http://api:3000
      - JENKINS_URL=http://admin:admin@jenkins:8080
    volumes:
      - ./services/jobwatch/src:/app/src
  node-packages-lerna:
    build: node-packages
    command: bash -c "lerna bootstrap && lerna run --parallel watch"
    volumes:
      - .:/app:delegated
