version: '2'
services:
  elasticsearch:
    build: services/elasticsearch
    user: '1000'
    environment:
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"
  kibana:
    build:
      context: .
      dockerfile: services/kibana/Dockerfile
    ports:
      - "5601:5601"
  logstash:
    build:
      context: .
      dockerfile: services/logstash/Dockerfile
    user: '1111722'