apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: daemonset-admin
rules:
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch