# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  nginx: ""
  php: ""

environmentType: production

imagePullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# This flag controls the injection of the pod securityContext values below.
# It is intended to assist with phased rollout of rootless workloads.
# It can be toggled via a build-time environment variable.
# LAGOON_FEATURE_ROOTLESS_WORKLOAD=disabled sets `rootless: false`. Any other
# value in the environment variable sets `rootless: true`.
rootless: true
podSecurityContext:
  fsGroup: 10001
  runAsGroup: 0
  runAsUser: 10000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  nginx:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 10m
      memory: 10Mi
  php:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 10m
      memory: 10Mi

nodeSelector: {}

tolerations: []

affinity: {}

inPodCronjobs: ""

configMapSha: ""
