{{- if .Values.server.setNotificationChannel.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}-set-notification-channel
spec:
  activeDeadlineSeconds: {{ default 300 .Values.server.setDatasource.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app: {{ template "grafana.fullname" . }}
        component: "{{ .Values.server.name }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "grafana.server.fullname" . }}-set-notification-channel
        image: "{{ .Values.server.setNotificationChannel.image }}"
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: grafana-admin-user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: grafana-admin-password
        args:
          - "http://$(ADMIN_USER):$(ADMIN_PASSWORD)@{{ template "grafana.fullname" . }}:{{ .Values.server.httpPort }}/api/alert-notifications"
          - "--max-time"
          - "10"
          - "-H"
          - "Content-Type: application/json;charset=UTF-8"
          - "-d"
          {{- with .Values.server.setNotificationChannel.channel }}
          - '{"name": "{{ .name }}",
              "type": "{{ .type }}",
              "settings": { "url": "{{ .url }}" },
              "isDefault": {{ .isDefault | default "null" }} }'
          {{- end }}
      restartPolicy: {{ .Values.server.setNotificationChannel.restartPolicy }}
{{- end -}}
