{{- if .Values.openshift -}}
{{- $releaseName := .Release.Name -}}
{{- $servicePort := .Values.server.service.httpPort -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}
spec:
  host: {{ .Values.server.ingress.hosts | first }}
  to:
    kind: Service
    name: {{ printf "%s-%s" $releaseName "grafana" | trunc 63 }}
    weight: 100
  wildcardPolicy: None
{{- end -}}
