apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template-node
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_SITEGROUP
    description: Which sitegroup this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to, original value
    required: true
  - name: AMAZEEIO_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: ROUTER_URL
    description: URL of the Router
    required: true
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${SERVICE_NAME}-volume
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      service: ${SERVICE_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          sitegroup: ${SAFE_SITEGROUP}
      spec:
        containers:
        - image: ' '
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 3000
            protocol: TCP
          ports:
          - containerPort: 15672
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            timeoutSeconds: 1
          env:
            - name: AMAZEEIO_GIT_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_BRANCH
            - name: AMAZEEIO_GIT_SAFE_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_SAFE_BRANCH
            - name: AMAZEEIO_GIT_SHA
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_GIT_SHA
            - name: AMAZEEIO_SITEGROUP
              valueFrom:
                configMapKeyRef:
                  name: amazeeio-env
                  key: AMAZEEIO_SITEGROUP
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: secret-environment
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-environment
                  key: RABBITMQ_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: ${SERVICE_NAME}-volume
        volumes:
        - name: ${SERVICE_NAME}-volume
          persistentVolumeClaim:
            claimName: ${SERVICE_NAME}-volume
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: 15672-tcp
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      service: ${SERVICE_NAME}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      sitegroup: ${SAFE_SITEGROUP}
    name: ${SERVICE_NAME}
  spec:
    host: ${SERVICE_NAME}.${ROUTER_URL}
    port:
      targetPort: 15672-tcp
    to:
      kind: Service
      name: ${SERVICE_NAME}
