apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template
parameters:
  - name: TAG
    description: Which docker image tag should be deployed
    required: true
  - name: NAME
    description: Name of the objects to create
    required: true
  - name: SHORT_NAME
    description: Shorter name of the objects to create, can be max 24 chars
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to
    required: true
  - name: ROUTER_URL
    description: URL of the Router
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: ' '
          name: nodejs
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-environment
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-environment
                  key: RABBITMQ_PASSWORD
            - name: JENKINS_URL
              valueFrom:
                secretKeyRef:
                  name: secret-environment
                  key: JENKINS_URL
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs
        from:
          kind: ImageStreamTag
          name: ${SITEGROUP}:${TAG}
      type: ImageChange
  status: {}