apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ template "trigger_quay_builds.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger-quay-builds
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: Always
            env:
              - name:  REPOSITORY
                value: {{ .Values.REPOSITORY }}
              - name:  TRIGGER_UUID
                value: {{ .Values.TRIGGER_UUID }}
              - name:  ROBOT_TOKEN
                valueFrom:
                  secretKeyRef: 
                    name: {{ template "trigger_quay_builds.fullname" . }}
                    key:  ROBOT_TOKEN
          restartPolicy: OnFailure


