apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-dpc-server
  namespace: metrics
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gluster
  volumeName: gluster-pv80
