{
 "title": "Projects",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Total Projects",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n COUNT(*)\nFROM project\nWHERE $__timeFilter(created)\n"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created) as time_sec,\n'New Projects' AS ‘metric’,\ncount(id)\nFROM project\nWHERE\n$__timeFilter(created)\nGROUP BY MONTH(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created) as time_sec,\n'Total Environments' AS ‘metric’,\ncount(id)\nFROM environment\nWHERE\n$__timeFilter(created)\nGROUP BY MONTH(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Lagoon Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(updated) as time,\n  'Total Environment Storage' as 'metric',\n  SUM(bytes_used)/1024/1024\nFROM\n  environment_storage\nWHERE\n  $__timeFilter(updated)\n  GROUP BY MONTH(updated)\n  ORDER BY updated"
    }
   ]
  },
  {
   "title": "Lagoon Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Lagoon Prod Hours",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  }
 ]
}