apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "mongo.fullname" . }}"
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
  annotations:
    {{- include "mongo.annotations" . | nindent 4 }}
  annotations:
    appuio.ch/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
